Enable to draw the curve eval only for a specific hue curve.
autodesk-forks/OpenColorIO pull request #11
Opened 2024-07-12 12:35 UTC by larochj

2024-07-17 05:02 UTC, doug-walker requested changes
This looks better, thanks.

2024-07-17 15:11 UTC, larochj commented on src/OpenColorIO/ops/gradinghuecurve/GradingHueCurveOpGPU.cpp
> +                        propNames.m_curveToDraw);
This code is from before I removed the Int, it is no longer in the PR

2024-07-17 16:54 UTC, larochj commented on include/OpenColorIO/OpenColorTransforms.h
> +    virtual void setCurveToDraw( HueCurveType curveToDraw ) = 0;
This code is from before I removed the Int, it is no longer in the PR

2024-07-17 17:07 UTC, larochj commented on src/OpenColorIO/ops/gradinghuecurve/GradingHueCurveOpGPU.cpp
>      switch (dir)
That's right, fixed

2024-07-17 17:12 UTC, larochj commented on include/OpenColorIO/OpenColorTransforms.h
Fixed

2024-07-17 17:33 UTC, larochj commented on src/OpenColorIO/ops/gradinghuecurve/GradingHueCurveOpData.cpp
> +        m_drawCurveOnly != rop->m_drawCurveOnly ||
Fixed, I aligned the != with the rest above

2024-07-18 02:41 UTC, doug-walker approved these changes
Looks good!

Sorry about some of the comments, they were left over from an earlier review and I didn't realize they got added to my review of your second pass.

2024-07-18 11:41 UTC, merged