RGB to HSY fixed functions using CPU
autodesk-forks/OpenColorIO pull request #17
Opened 2024-07-18 22:39 UTC by larochj

2024-07-19 05:59 UTC, doug-walker requested changes

2024-07-19 05:59 UTC, doug-walker commented on src/OpenColorIO/ops/fixedfunction/FixedFunctionOpCPU.cpp
> +    applyRGBToHSY(inImg, outImg, numPixels, MIN_0);
You need an applyHSYToRGB, with a corresponding implementation above.

2024-07-19 05:59 UTC, doug-walker commented on tests/cpu/ops/fixedfunction/FixedFunctionOpCPU_tests.cpp
> +    //TODO: Change the data
Please refer to SynColor CPURenderer_cases.cpp_inc lines 7204 through 7438.
CPURendererFunction_RGBTOHSY_LOG -- For this test, divide the input values by 4095 and the output values by 65535 in order to convert them to floats.
CPURendererFunction_RGBTOHSY_LIN

2024-07-19 12:58 UTC, larochj commented on src/OpenColorIO/ops/fixedfunction/FixedFunctionOpCPU.cpp
> +    applyRGBToHSY(inImg, outImg, numPixels, MIN_0);
Oh true, I only made one part of the convertion, thanks!

2024-07-19 16:12 UTC, larochj commented on src/OpenColorIO/ops/fixedfunction/FixedFunctionOpCPU.cpp
> +    applyRGBToHSY(inImg, outImg, numPixels, MIN_0);
Fixed, but I still get a failure for the test style_RGB_TO_HSY_LIN_inv.
Any Idea why?

2024-07-19 16:15 UTC, larochj commented on tests/cpu/ops/fixedfunction/FixedFunctionOpCPU_tests.cpp
> +    //TODO: Change the data
Fixed, used the data from SynColor for Lin and Log.
But I did not find any test for vid.

2024-07-20 04:23 UTC, doug-walker reviewed
Please let me know which tests pass and paste the results for any that don't.

2024-07-20 04:23 UTC, doug-walker commented on tests/cpu/ops/fixedfunction/FixedFunctionOpCPU_tests.cpp
> +    ApplyFixedFunction(&img[0], &hsyFrame[0], 4, dataFwdLin, 1e-6f, __LINE__);
The tolerance in SynColor was 1e-4, is it passing at 1e-6?

2024-07-20 04:23 UTC, doug-walker commented on tests/cpu/ops/fixedfunction/FixedFunctionOpCPU_tests.cpp
> +    //TODO: Change the data
It looks like there was not a test for vid in SynColor.  Looks like you made one, which is fine.

2024-07-20 04:23 UTC, doug-walker commented on src/OpenColorIO/ops/fixedfunction/FixedFunctionOpCPU.cpp
> +    applyRGBToHSY(inImg, outImg, numPixels, MIN_0);
I looked at the code but did not notice a problem. The tolerance you're using is tighter than SynColor. It might help if you paste the results into the thread here.

2024-07-22 11:50 UTC, larochj commented on src/OpenColorIO/ops/fixedfunction/FixedFunctionOpCPU.cpp
> +    applyRGBToHSY(inImg, outImg, numPixels, MIN_0);
Here it is:
```
[ 49/230] [FixedFunction / style_RGB_TO_HSY_LIN_inv          ] - FAILED - 
Maximum error: 45990.25 at pixel: 63694 on component 2 larger than epsilon.
scr = {1.915679932, 1.915691376, 1.91570282, 1.915714264}
cpu = {-1317085.375, 736788.9375, -3420181.75, 1.915714264}
gpu = {-1334796.875, 746696.5625, -3466172, 1.915714264}
absolute tolerance=9.999999747e-05
```

2024-07-22 11:58 UTC, larochj commented on tests/cpu/ops/fixedfunction/FixedFunctionOpCPU_tests.cpp
> +    ApplyFixedFunction(&img[0], &hsyFrame[0], 4, dataFwdLin, 1e-6f, __LINE__);
Yes they all pass exept style_RGB_TO_HSY_LIN_inv. 
And the error margin is bigger than 1e-4:
```
[ 49/230] [FixedFunction / style_RGB_TO_HSY_LIN_inv          ] - FAILED - 
Maximum error: 45990.25 at pixel: 63694 on component 2 larger than epsilon.
scr = {1.915679932, 1.915691376, 1.91570282, 1.915714264}
cpu = {-1317085.375, 736788.9375, -3420181.75, 1.915714264}
gpu = {-1334796.875, 746696.5625, -3466172, 1.915714264}
absolute tolerance=9.999999747e-05
```

2024-07-23 04:27 UTC, doug-walker commented on tests/cpu/ops/fixedfunction/FixedFunctionOpCPU_tests.cpp
> +    ApplyFixedFunction(&img[0], &hsyFrame[0], 4, dataFwdLin, 1e-6f, __LINE__);
Hi Jonathan.  Looks like you pasted the result of the GPU test.  Let's start with the CPU tests.  Would you please paste the four input and output values?

2024-07-23 12:47 UTC, larochj commented on tests/cpu/ops/fixedfunction/FixedFunctionOpCPU_tests.cpp
> +    ApplyFixedFunction(&img[0], &hsyFrame[0], 4, dataFwdLin, 1e-6f, __LINE__);
All CPU test passes:
```
[ 667/1091] [FixedFunctionOpCPU / RGB_TO_HSY_LIN                         ] - PASSED
[ 668/1091] [FixedFunctionOpCPU / RGB_TO_HSY_LOG                         ] - PASSED
[ 669/1091] [FixedFunctionOpCPU / RGB_TO_HSY_VID                         ] - PASSED
[ 688/1091] [FixedFunctionOps / RGB_TO_HSY_LIN                           ] - PASSED
[ 689/1091] [FixedFunctionOps / RGB_TO_HSY_LOG                           ] - PASSED
[ 690/1091] [FixedFunctionOps / RGB_TO_HSY_VID                           ] - PASSED
```

For HSY lin here are the value used in the CPU test
tests/cpu/ops/fixedfunction/FixedFunctionOpCPU_tests.cpp
```
    const std::vector<float> hsyFrame {
         4.70554752e-01f, 9.12594033f, 3.26650218e-02f, 0.f,
         0.75f,           0.22196741f, 0.38596f,        1.f,
         0.08333333f,     0.12976444f, 0.034974f,       0.f,
         0.96296296f,     9.7034f,     -0.1862f,        1.f };

    const std::vector<float> rgbFrame {
        -0.075290f,  0.078996f, -0.108397f, 0.f,
         0.3f,       0.4f,       0.5f,      1.f,
         0.05f,      0.03f,      0.04f,     0.f,
         0.3f,      -0.4f,       0.5f,      1.f };
```

2024-07-23 22:22 UTC, doug-walker commented on tests/cpu/ops/fixedfunction/FixedFunctionOpCPU_tests.cpp
> +    ApplyFixedFunction(&img[0], &hsyFrame[0], 4, dataFwdLin, 1e-6f, __LINE__);
OK, that's confusing.  Above you wrote that style_RGB_TO_HSY_LIN_inv was not passing, but now it is?  

If it is, that means we should be able to rely on the CPU values for comparison against the GPU tests.

The GPU result you pasted in a different thread had a very extreme output value.  If the GPU matches the CPU through the normal range of values, that is the main criteria.  If they diverge only at extreme values, that would not be too surprising given that it's a separate implementation.  We don't need to fix that.  You could limit the GPU test input values or perhaps adjust the parameter values so that it passes.

2024-07-25 20:31 UTC, doug-walker approved these changes

2024-07-26 13:02 UTC, merged