Lut-free built-ins
autodesk-forks/OpenColorIO pull request #18
Opened 2024-07-20 01:24 UTC by cozdas

- WIP Fixed-function for PQ<->Linear function. Doesn't have the GPU implementation yet and the rest may need tweaks.

2024-07-20 05:03 UTC, doug-walker reviewed
I need to review more thoroughly, but you're on the right track.

There's a lot more to adding a new FixedFunction though.  CTF support and Python support are required. Version checks must be updated to not allow the additions in config versions lower than 2.4.  Unit tests must be added to test all of that.

Some of the other PRs that might be a useful reference are #1404, #1814, and #896.

2024-08-01 04:24 UTC, cozdas commented on src/OpenColorIO/transforms/builtins/Displays.cpp
>          registry.addBuiltin("CURVE - ST-2084_to_LINEAR",
Now we have the "CURVE - ST-2084_to_LINEAR" built-in transform and the PQ_TO_LINEAR built-in fixed function op. To me it feels like they are a bit redundant now. Are they?

2024-08-01 04:30 UTC, cozdas commented on tests/gpu/GPUUnitTest.cpp
> +                tmp.m_inputValues[idx] = min + step * float(i);
This was a bug: "step" was calculated using the remaining numEntries, but was multiplied by array index with the last element being (predefinedNumEntries-1). This was omitting the lower end values and over-shooting the specified max-value. This confused me a while.

2024-08-12 03:32 UTC, doug-walker requested changes
Please update tests/cpu/Config_tests.cpp, fixed_function_serialization, around line 4795 to validate Yaml serialization. Then add a check (there are other examples in that test) that an exception will be thrown on validation if the version is less than 2.4.

Please update tests/cpu/fileformats/FileFormatCTF_tests.cpp, ff_load_save_ctf, around line 3841 to validate CTF serialization.

I'm realizing that we have not been as rigorous on CTF versioning as we have on config versioning. Given that we are adding a lot for 2.4 we should bump the CTF version. This could be done in a follow-up.

2024-08-13 02:59 UTC, cozdas commented on src/OpenColorIO/ops/fixedfunction/FixedFunctionOpCPU.cpp
> +            // TODO: we may want to implement an SIMD renderer if scalar performance is low.
Agreed but please ignore all these cosmetic/style issues and temporary items for now. 

As I mentioned, the current state of the PR is for me to discover/learn all the parts that need to be updated for adding fixed-function built-ins and replacing the built-in transforms to use them. This is why I tried to keep this PR simple with only one sample function implemented (PQ), so that it'd be easier for both of us to iterate over this. Once we're happy with all the functional items in place, then I'll add the other built-in functions with proper formatting, and will do the code cleanup and beautifications. This is a WIP PR and trying to keep the formatting matching with the conventions (sometimes there seems to be multiple in a single file) is breaking the flow especially when my editor has different ideas about the conventions.

I think we need to come up with a clang format file and make it part of the repo, this way manual handing both for the code author and the reviewer will be unnecessary. I'm seeing that reformat requests are verry common in all PRs in the main repo too. Food for thought.

2024-08-13 02:59 UTC, cozdas commented on src/OpenColorIO/ops/fixedfunction/FixedFunctionOpCPU.cpp
> +    using FLOAT = double; // Temp: used for fast float/double switching for precision evaluation.
This is a temp thing, please ignore for now.

2024-08-13 03:01 UTC, cozdas commented on src/OpenColorIO/ops/fixedfunction/FixedFunctionOpCPU.cpp
> +            float nits100 = float(FLOAT(100.0) * std::pow(std::max(FLOAT(0), x - c1) / (c2 - c3 * x), FLOAT(1.) / m1));
I'm pretty sure that in this form the compiler will optimize it (unless we have very strict, non-standard floating point handling flags set for the compilers). I'll double check in the final form.

2024-08-13 03:03 UTC, cozdas commented on src/OpenColorIO/ops/fixedfunction/FixedFunctionOpGPU.cpp
> +    ss.newLine() << "x = max(x, " << ss.float3Const(0.0) << ");";
Yup, leftover from the pre-symmetry implementation.  good catch.

2024-08-13 03:04 UTC, cozdas commented on src/OpenColorIO/ops/fixedfunction/FixedFunctionOpGPU.cpp
> +    // TODO: this still clamps negative inputs
leftover too, will be cleaned in the final cleanup pass.

2024-08-13 03:05 UTC, cozdas commented on src/OpenColorIO/transforms/builtins/Displays.cpp
We can always bring that back, in the final form of the PR based on the perf test results. I tried to keep the PR body short for easier review/iteration.

2024-08-13 03:12 UTC, cozdas commented on src/OpenColorIO/transforms/builtins/Displays.cpp
>          registry.addBuiltin("CURVE - ST-2084_to_LINEAR",
I think my question was, if we didn't have the build-in transform, then ideally, we'd have only the fixed-function implementation which could be used the config files directly. Currently both the built-in transform and the fixed-function will be almost identical and we need to built-in transform just for backward compatibility.  Is my understanding correct?

2024-08-13 03:17 UTC, cozdas commented on tests/gpu/FixedFunctionOp_test.cpp
> +    test.setTestWideRange(false);
Yes, it blows up, thus the narrow-range test. Maybe we can also utilize the ExpectedMinimalValue to keep the large errors under threshold, but extending the test-framework to accept custom ranges will be a better, more generic and controllable approach in my opinion too.

2024-08-13 04:08 UTC, doug-walker commented on src/OpenColorIO/transforms/builtins/Displays.cpp
>          registry.addBuiltin("CURVE - ST-2084_to_LINEAR",
Yes, there will be both a Builtin Transform and FixedFunction that will be very similar in functionality but they are both required.

2024-08-13 04:52 UTC, cozdas commented on tests/cpu/fileformats/FileFormatCTF_tests.cpp
> +    ValidateFixedFunctionStyleNoParam(OCIO::FixedFunctionOpData::PQ_TO_LINEAR       , __LINE__);
@doug-walker 
You requested CTF serialization implementation: "Please update tests/cpu/fileformats/FileFormatCTF_tests.cpp, ff_load_save_ctf, around line 3841 to validate CTF serialization."

This test was already extended to cover the new fixed-functions. What else do we want to test here?

2024-08-24 01:58 UTC, doug-walker requested changes

2024-08-24 01:58 UTC, doug-walker commented on src/OpenColorIO/transforms/builtins/Displays.cpp
The OCIO coding style does not indent for namespace.

2024-08-24 01:58 UTC, doug-walker commented on src/OpenColorIO/transforms/builtins/Displays.cpp
> +                    // TODO: do we want remove clamp at 1 too per issue #1968 ?
Remove the clamp on both ends.

2024-08-24 01:58 UTC, doug-walker commented on src/apps/ocioconvert/main.cpp
> +            }
This would be better in ocioperf, but no strong objection, if it helps you.

2024-08-24 01:58 UTC, doug-walker commented on src/OpenColorIO/ops/fixedfunction/FixedFunctionOpCPU.cpp
> +    // Input is in nits/100, convert to [0,1], where 1 is 10000 nits.
Still needs to move.

2024-08-24 01:58 UTC, doug-walker commented on src/OpenColorIO/ops/fixedfunction/FixedFunctionOpCPU.cpp
> +            if(CPUInfo::instance().hasSSE2())
We assume all CPUs have at least SSE2, so this check is confusing. If people don't want that, they need to not set OCIO_USE_SSE2.

2024-08-24 01:58 UTC, doug-walker commented on src/OpenColorIO/ops/fixedfunction/FixedFunctionOpCPU.cpp
> +                return std::make_shared<Renderer_PQ_TO_LINEAR_SSE<false>>(func);
Is seuqential a word?

2024-08-24 01:58 UTC, doug-walker commented on tests/cpu/ops/fixedfunction/FixedFunctionOpCPU_tests.cpp
> +    ApplyFixedFunction(&img[0], &inputFrame[0], NumPixels, dataFInv, 1e-5f, __LINE__);
It would be nice to test both the fastpow and non-fastpow implementations.

2024-08-26 19:16 UTC, cozdas commented on src/OpenColorIO/ops/fixedfunction/FixedFunctionOpCPU.cpp
> +            if(CPUInfo::instance().hasSSE2())
We have the same logic in Lut1DOpCPU.cpp line 283 and Lut3DOpCPU.cpp line 390. 
Do you want me to remove those run-time-checks too?

2024-08-26 19:21 UTC, cozdas commented on src/apps/ocioconvert/main.cpp
> +            }
Since ocioconvert is reporting the render duration in the verbose mode for CPU, I added it for GPU too to make it consistent. 

But I hit a problem with MacOS. Looks like GL_TIME_ELAPSED, is not implemented by MacOS even though it's part of  9-year old OpenGL 3.2 spec. Probably it's why this was not implemented in either of the command line tools in ocio. I had to roll this feature back :/

2024-08-26 19:21 UTC, cozdas commented on src/OpenColorIO/ops/fixedfunction/FixedFunctionOpCPU.cpp
> +                return std::make_shared<Renderer_PQ_TO_LINEAR_SSE<false>>(func);
LOL no! good catch of my typo :)

2024-08-26 19:24 UTC, cozdas commented on src/OpenColorIO/ops/fixedfunction/FixedFunctionOpCPU.cpp
> +    // Input is in nits/100, convert to [0,1], where 1 is 10000 nits.
Yeah this PR is still in the draft mode, doing the final cleanups now. I'll poke you when it's ready for another round.

2024-08-27 03:44 UTC, doug-walker commented on src/OpenColorIO/ops/fixedfunction/FixedFunctionOpCPU.cpp
> +            if(CPUInfo::instance().hasSSE2())
We never had that until Mark Reid implemented all the AVX stuff. It kind of makes sense in that context where he has all the different versions. But there are a bunch of other places in the code that simply assume that if OCIO_USE_SSE2 that SSE2 may be used.  If the extra function call only happens every scan line, it's probably ok, but some people do use the scalar applyRGB to process images, so in that scenario it might add a significant penalty?

2024-08-27 04:10 UTC, cozdas commented on src/OpenColorIO/ops/fixedfunction/FixedFunctionOpCPU.cpp
> +            if(CPUInfo::instance().hasSSE2())
Normally it should be a single, inlined mask check but the way it's implemented currently doesn't seem to be inline-able. performance wise it should still be unnoticeable amongst all the other prep work we do until we reach here but these checks are not very useful indeed while the rest of the system assume SSE is available at run-time.  Though it would be a cleaner/consistent approach if we had the same logic for SSE and AVX and all the other instruction sets. 

I'm removing these checks then. Not touching the preexisting Lut code though.

2024-08-27 19:08 UTC, doug-walker approved these changes

2026-04-18 21:33 UTC, closed without merging