Fix identity hue curve draw only
autodesk-forks/OpenColorIO pull request #20
Opened 2024-07-26 20:00 UTC by larochj

Right now we can't draw identity hue curve that are different from the hue-sat curve.

The reason is we do not set knots and coefs for identity curves when computing the curves, after this in the shader we set a constant identity value that is not correct for all the hue curves (Like diagonals and horizontal 0).

With this change list, we 2 knots with coefs that fits a linear or constant curve as required.

2024-08-04 22:06 UTC, doug-walker requested changes

2024-08-04 22:06 UTC, doug-walker commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
> +        const int N_IDENTITY_COEFS = 6;
If there are 2 knots, there would be 3 coefs.

2024-08-04 22:06 UTC, doug-walker commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
> +        // Identity curve are linear or constant.
Identity curve are linear or constant, so set the quadratic coefficient to zero.

2024-08-04 22:06 UTC, doug-walker commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
> +        // Set the identity curve constant
Set the constant coefficient for an identity curve.

2024-08-04 22:06 UTC, doug-walker commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
> +                                   1.0f : 0.f;
The hue-fx curve is Periodic but has an identity value of 0.

2024-08-05 11:52 UTC, larochj commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
> +                                   1.0f : 0.f;
So this code is alright as it is? hue-fx has the type BSplineCurveType::PERIODIC_0_B_SPLINE so it will have a constant coef of 0.0f.
`const GradingBSplineCurveImpl GradingHueCurveImpl::DefaultHueHue(DefaultHueHueCtrl, BSplineCurveType::HUE_HUE_B_SPLINE );
const GradingBSplineCurveImpl GradingHueCurveImpl::DefaultHueSat(DefaultHueSatCtrl, BSplineCurveType::PERIODIC_1_B_SPLINE );
const GradingBSplineCurveImpl GradingHueCurveImpl::DefaultHueFx(DefaultHueFxCtrl, BSplineCurveType::PERIODIC_0_B_SPLINE );
const GradingBSplineCurveImpl GradingHueCurveImpl::DefaultLumSat(DefaultLumSatCtrl, BSplineCurveType::HORIZONTAL1_B_SPLINE);
const GradingBSplineCurveImpl GradingHueCurveImpl::DefaultLumSatLin(DefaultLumSatLinCtrl, BSplineCurveType::HORIZONTAL1_B_SPLINE);
const GradingBSplineCurveImpl GradingHueCurveImpl::DefaultSatSat(DefaultSatSatCtrl, BSplineCurveType::DIAGONAL_B_SPLINE);
const GradingBSplineCurveImpl GradingHueCurveImpl::DefaultSatLum(DefaultSatLumCtrl, BSplineCurveType::HORIZONTAL1_B_SPLINE);
const GradingBSplineCurveImpl GradingHueCurveImpl::DefaultLumLum(DefaultLumLumCtrl, BSplineCurveType::DIAGONAL_B_SPLINE);
const GradingBSplineCurveImpl GradingHueCurveImpl::DefaultLumLumLin(DefaultLumLumLinCtrl, BSplineCurveType::DIAGONAL_B_SPLINE);`

2024-08-05 12:16 UTC, larochj commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
> +        const int N_IDENTITY_COEFS = 6;
Fixed

2024-08-05 12:18 UTC, larochj commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
> +        // Set the identity curve constant
Fixed, added to the comment

2024-08-07 02:04 UTC, doug-walker requested changes

2024-08-07 14:10 UTC, larochj commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
> +        // Set the identity curve constant
Fixed, added the linear comment on top of the linearCoef declaration and moved to the comment about the constant coef on top of the const constantCoef declaration.

2024-08-07 14:11 UTC, larochj commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
> +        // Set the identity curve constant
Fixed

2024-08-07 16:06 UTC, doug-walker approved these changes

2024-08-07 16:14 UTC, merged