Adding support for commas in active views list
autodesk-forks/OpenColorIO pull request #26
Opened 2024-12-10 22:43 UTC by larochj

Added a set/get/clear/remove for the active views and displays.
Made changes to the YAML save to avoid repeating the parsing of the string list.

2024-12-11 04:29 UTC, doug-walker requested changes
Thanks for adding this Jonathan, I think it will be very helpful for OCIO!

Please add unit tests in tests/cpu/ParseUtils_tests.cpp. This should include the various edge cases, including unmatched quotes.

2024-12-11 04:29 UTC, doug-walker commented on src/OpenColorIO/Config.cpp
> +    }
I'm wondering if we should throw here? Some of the other remove*() functions throw if the name is not found.

2024-12-11 04:29 UTC, doug-walker commented on src/OpenColorIO/Config.cpp
> +    getImpl()->m_activeDisplays.push_back(view);
We should perhaps check if it's already in the list before adding a duplicate?

2024-12-11 04:29 UTC, doug-walker commented on src/OpenColorIO/Config.cpp
> +void Config::addActiveDisplay(const char * view)
Minor, but it would be nice if the ordering of the functions was consistent between displays and views. Perhaps move this up above removeActiveDisplay?

2024-12-11 04:29 UTC, doug-walker commented on src/OpenColorIO/Config.cpp
> +    }
I was wondering if we should throw, but this is fine. It's consistent with getDisplay(index).

2024-12-11 16:48 UTC, larochj commented on src/OpenColorIO/ParseUtils.cpp
> +            result += "\"" + val + "\", ";
Fixed, now the condition check the boundaries if there is quotes

2024-12-11 16:52 UTC, larochj commented on src/OpenColorIO/ParseUtils.cpp
> +                isEndFound = true;
Right now the quote get included in the last name.
But yes I can make it throw if we don't want any name using quotes to avoid any parsing error afterward

2024-12-11 16:53 UTC, larochj commented on src/OpenColorIO/OCIOYaml.cpp
>      out << YAML::Value << YAML::Flow << active_views;
Not sure if it is caused by the YAML::Flow, but yes the operator<< into a YAM::Emiter handle the quoting

2024-12-11 17:05 UTC, larochj commented on src/OpenColorIO/ParseUtils.cpp
> +    }
Fixed, changed it to handle the first element like  StringUtils::Join

2024-12-12 00:30 UTC, larochj commented on src/OpenColorIO/Config.cpp
> +    }
Fixed, it throw an exception now

2024-12-12 00:31 UTC, larochj commented on src/OpenColorIO/Config.cpp
> +    getImpl()->m_activeDisplays.push_back(view);
Fixed, an exception is thrown on a duplicate now

2024-12-12 00:31 UTC, larochj commented on src/OpenColorIO/Config.cpp
> +void Config::addActiveDisplay(const char * view)
Fixed

2024-12-12 00:32 UTC, larochj commented on src/OpenColorIO/Config.cpp
> +    }
I have left it unchanged since it fit with similar calls

2024-12-12 04:23 UTC, doug-walker requested changes

2024-12-12 04:23 UTC, doug-walker commented on src/OpenColorIO/ParseUtils.cpp
> +                isEndFound = true;
Yes, let's throw.

2024-12-12 04:23 UTC, doug-walker commented on tests/cpu/ParseUtils_tests.cpp
> +    OCIO_CHECK_EQUAL( "This, \"is   \":   a:   test\"", OCIO::JoinStringEnvStyle(outputvec) );
Please add more tests that use commas and quotes, such as:
outputvec = { "This", "is:   ", "\"a very good,\"", " fine, helpful, and useful ", "test" };

2024-12-12 04:23 UTC, doug-walker commented on src/OpenColorIO/Config.cpp
> +void Config::addActiveDisplay(const char * view)
The argument to the function should be "display", not "view".

2024-12-12 04:23 UTC, doug-walker commented on src/OpenColorIO/Config.cpp
> +    }
The addActiveView should have the same behavior. Please compare all of your new display functions with the view functions and make sure they behave the same.

2024-12-12 15:13 UTC, larochj commented on src/OpenColorIO/LookParse.cpp
> +        }
This test failure sums up why it might be needed:
```
/Users/larochj/Documents/Git/adsk-ocio-fork/tests/cpu/FileRules_tests.cpp:62:
FAILED: ss.str() == std::string(CONFIG)
	values were 'ocio_profile_version: 1

search_path: ""
strictparsing: false
luma: [0.2126, 0.7152, 0.0722]

roles:
  default: raw

displays:
  sRGB:
    - !<View> {name: Raw, colorspace: raw}

active_displays: [""]
active_views: [""]

colorspaces:
  - !<ColorSpace>
    name: raw
    family: ""
    equalitygroup: ""
    bitdepth: unknown
    isdata: false
    allocation: uniform
' and 'ocio_profile_version: 1

search_path: ""
strictparsing: false
luma: [0.2126, 0.7152, 0.0722]

roles:
  default: raw

displays:
  sRGB:
    - !<View> {name: Raw, colorspace: raw}

active_displays: []
active_views: []

colorspaces:
  - !<ColorSpace>
    name: raw
    family: ""
    equalitygroup: ""
    bitdepth: unknown
    isdata: false
    allocation: uniform
'
```

2024-12-12 15:24 UTC, larochj commented on src/OpenColorIO/LookParse.cpp
> +        }
We can assume an empty string to be an empty list 
Or 
an empty string to be a list containing an empty element.

For the looks it make sense to assume a list with one empty element.
For the active views and active displays, we might want to consider this an empty list.

I found an alternative to avoid changing the look parser.
Instead I let the split assume an empty string to be a list containing 1 empty element
and the getNumActiveView and display would verify the single element:
```
int Config::getNumActiveViews() const
{
    const int numActiveViews = static_cast<int>(getImpl()->m_activeViews.size());
    if( numActiveViews == 1 && 
        !getImpl()->m_activeViews[0].empty() )
    {
        return 0;
    }
    
    return static_cast<int>(getImpl()->m_activeViews.size());
}
```

We can also let users verify themselves if there is a single empty element.

2024-12-12 16:05 UTC, larochj commented on src/OpenColorIO/Config.cpp
> +    }
Fixed

2024-12-12 16:05 UTC, larochj commented on src/OpenColorIO/Config.cpp
> +void Config::addActiveDisplay(const char * view)
Fixed

2024-12-12 17:18 UTC, larochj commented on tests/cpu/ParseUtils_tests.cpp
> +    OCIO_CHECK_EQUAL( "This, \"is   \":   a:   test\"", OCIO::JoinStringEnvStyle(outputvec) );
Added this test case and another one

2024-12-12 17:19 UTC, larochj commented on src/OpenColorIO/ParseUtils.cpp
> -    else
Fixed, added the separator char as a parameter

2024-12-12 17:20 UTC, larochj commented on tests/cpu/ParseUtils_tests.cpp
> +    OCIO_CHECK_EQUAL("test", outputvec[3]);
Fix, it is either colon or comma

2024-12-13 02:36 UTC, doug-walker requested changes

2024-12-13 02:36 UTC, doug-walker commented on tests/cpu/ParseUtils_tests.cpp
> +    OCIO_CHECK_EQUAL( "This, \"is   \":   a:   test\"", OCIO::JoinStringEnvStyle(outputvec) );
Actually, please make the first word "\"This\"", to test that quotes are omitted when they aren't necessary.

2024-12-13 02:36 UTC, doug-walker commented on tests/cpu/ParseUtils_tests.cpp
> +    outputvec = OCIO::SplitStringEnvStyle("   \"This  , is   \":   a:   test  ");
Please add:
// If the string contains a comma, it is chosen as the separator character rather than the colon (even if it is within quotes and therefore not used as such).

2024-12-13 02:36 UTC, doug-walker commented on src/OpenColorIO/ParseUtils.cpp
> +// The element of the list are separeted by ":" or ",".
Update comment.

2024-12-13 02:36 UTC, doug-walker commented on src/OpenColorIO/LookParse.cpp
> +        }
Please update the getNumActive* functions to return 0 for an empty string.

However, it looks like your current SplitStringEnvStyle is already returning a StringVec with one empty string, which seems like the same thing as the previous SplitStringEnvStyle. So I guess you could have already removed this change to LookParse?

2024-12-13 05:18 UTC, larochj commented on src/OpenColorIO/LookParse.cpp
> +        }
Just fixed it, it was partly fixed at the time of your review I had found issues midway.

2024-12-13 05:22 UTC, larochj commented on tests/cpu/ParseUtils_tests.cpp
> +    OCIO_CHECK_EQUAL( "This, \"is   \":   a:   test\"", OCIO::JoinStringEnvStyle(outputvec) );
Join would not remove the quotes in this case, but it would not add another around a string that is already surrounded by quotes. I would expect split to remove the quotes (not join).

I changed two test case to touch what I just described.

2024-12-13 05:28 UTC, larochj commented on tests/cpu/ParseUtils_tests.cpp
> +    outputvec = OCIO::SplitStringEnvStyle("   \"This  , is   \":   a:   test  ");
Fixed

2024-12-13 05:28 UTC, larochj commented on src/OpenColorIO/ParseUtils.cpp
> +// The element of the list are separeted by ":" or ",".
Fixed

2024-12-13 07:10 UTC, doug-walker approved these changes
If you're able to fix the Windows CI failure, that would be great. Otherwise, go ahead and merge and I will fix it before submitting to OCIO.

Don't worry about the other CI failures. I need to pull over the latest Actions workflow from OCIO main to get that working again on our branch.

2024-12-13 15:00 UTC, merged