Hue Curve Transform GPU
autodesk-forks/OpenColorIO pull request #5
Opened 2024-06-06 20:20 UTC by larochj

2024-06-07 04:44 UTC, doug-walker requested changes
Good progress!  I'm only about half way through the review, but here are my comments so far.

2024-06-07 04:44 UTC, doug-walker commented on src/OpenColorIO/ops/gradingrgbcurve/GradingRGBCurveOp.cpp
> -
Revert extra line.

2024-06-07 04:44 UTC, doug-walker commented on src/OpenColorIO/transforms/HueCurveTransform.h
> +#endif  // INCLUDED_OCIO_GRADINGPRIMARYTRANSFORM_H
Unmatched endif.

2024-06-07 04:44 UTC, doug-walker commented on src/OpenColorIO/transforms/HueCurveTransform.cpp
> +
Remove double new-line.

2024-06-07 04:44 UTC, doug-walker commented on src/OpenColorIO/transforms/HueCurveTransform.cpp
> +// TODO: Duplicated from GradingRGB, should it be accessible here?
Yes, please follow GradingRGB here.

2024-06-07 04:44 UTC, doug-walker commented on src/OpenColorIO/ops/gradingrgbcurve/HueCurveOpGPU.cpp
> +    st.newLine() << "float hueSatGain = max(0., " << props.m_eval << "(1, outColor.r, 1.));";    // HUE-SAT
You may not use "outColor", you need to call the function to get the name.

2024-06-07 04:44 UTC, doug-walker commented on src/OpenColorIO/ops/gradingrgbcurve/HueCurve.cpp
> +// SPDX-License-Identifier: BSD-3-Clause
Please create a "gradinghuecurve" directory at the same level as "gradingrgbcurve" and move all of your HueCurve*.* modules into there. And change the file names from HueCurve* to GradingHueCurve*.

2024-06-07 04:44 UTC, doug-walker commented on vendor/aftereffects/vc/vc15/OpenColorIO.vcxproj
> +    <ClInclude Include="..\..\..\..\src\OpenColorIO\ops\gradingrgbcurve\HueCurve.h" />
Please revert this file.

2024-06-07 04:48 UTC, doug-walker commented
It doesn't seem like adding the CPU renderer would be that much more work. Perhaps it would be worth it in order to enable the GPU unit tests.  (I had thought we had a way to test the GPU results on their own, but maybe I was thinking of SynColor.)

2024-06-07 18:27 UTC, larochj commented on include/OpenColorIO/OpenColorTransforms.h
> +    static GradingBSplineCurveRcPtr Create(std::initializer_list<GradingControlPoint> values, BSplineCurveType curveType = B_SPLINE);
Fixed it, made new Creates/Constructors and the old ones assume the type is BSpline

2024-06-07 18:30 UTC, larochj commented on include/OpenColorIO/OpenColorTransforms.h
> +class OCIOEXPORT HueCurve
Fixed it, no problems, I tough the same when I saw the Grading prefix before primaries and tone but forgot to change it in the end

2024-06-07 18:32 UTC, larochj commented on include/OpenColorIO/OpenColorTransforms.h
> +    static HueCurveRcPtr Create(const std::array<ConstGradingBSplineCurveRcPtr, HUE_NUM_CURVES> & curves);
Fixed it, I'm using a struct instead, I'm not too sure about the naming of it, but the goal is to avoid having 8 parameters to the constructors. I can use the parameters directly if it is prefered

2024-06-07 18:33 UTC, larochj commented on include/OpenColorIO/OpenColorTransforms.h
>  };
Fixed it

2024-06-07 18:33 UTC, larochj commented on include/OpenColorIO/OpenColorTypes.h
> +    TRANSFORM_TYPE_HUE_CURVE
Fixed it

2024-06-07 18:33 UTC, larochj commented on src/OpenColorIO/ops/fixedfunction/FixedFunctionOpGPU.cpp
> +    ss.newLine() << "float luma = dot(outColor.rgb, lumaWeights);";
Fixed it

2024-06-07 18:34 UTC, larochj commented on src/OpenColorIO/ops/fixedfunction/FixedFunctionOpGPU.cpp
> +    if (min0 > 0.)
Fixed it

2024-06-07 18:34 UTC, larochj commented on src/OpenColorIO/ops/gradingrgbcurve/GradingRGBCurveOp.cpp
> -
Fixed it

2024-06-07 18:34 UTC, larochj commented on src/OpenColorIO/transforms/HueCurveTransform.h
> +#endif  // INCLUDED_OCIO_GRADINGPRIMARYTRANSFORM_H
Fixed it

2024-06-07 18:34 UTC, larochj commented on src/OpenColorIO/transforms/HueCurveTransform.cpp
> +
Fixed it

2024-06-07 18:36 UTC, larochj commented on src/OpenColorIO/transforms/HueCurveTransform.cpp
> +// TODO: Duplicated from GradingRGB, should it be accessible here?
Removed the comment instead, It was a leftover I forgot to remove, I'm using the same functions as GradingRGB for BSpline and Control points, I'm just not redeclaring it.

2024-06-07 18:36 UTC, larochj commented on src/OpenColorIO/ops/gradingrgbcurve/HueCurveOpGPU.cpp
> +    st.newLine() << "float hueSatGain = max(0., " << props.m_eval << "(1, outColor.r, 1.));";    // HUE-SAT
Fixed it

2024-06-07 18:36 UTC, larochj commented on src/OpenColorIO/ops/gradingrgbcurve/HueCurve.cpp
> +// SPDX-License-Identifier: BSD-3-Clause
Moved the files to their own folders

2024-06-07 18:37 UTC, larochj commented on vendor/aftereffects/vc/vc15/OpenColorIO.vcxproj
> +    <ClInclude Include="..\..\..\..\src\OpenColorIO\ops\gradingrgbcurve\HueCurve.h" />
Reverted the whole file

2024-06-07 18:37 UTC, larochj commented
> It doesn't seem like adding the CPU renderer would be that much more work. Perhaps it would be worth it in order to enable the GPU unit tests. (I had thought we had a way to test the GPU results on their own, but maybe I was thinking of SynColor.)

2024-06-07 18:41 UTC, larochj commented
> It doesn't seem like adding the CPU renderer would be that much more work. Perhaps it would be worth it in order to enable the GPU unit tests. (I had thought we had a way to test the GPU results on their own, but maybe I was thinking of SynColor.)

I'll have a look at it! Thanks!

2024-06-08 02:08 UTC, doug-walker requested changes
Reviewed some of the remaining modules. It's looking good, I only found a bunch of minor typos.  Requested a few more name changes to better match the existing RGB curve code.  Making good progress!

2024-06-08 02:08 UTC, doug-walker commented on tests/cpu/ops/gradingrgbcurve/HueCurveOpData_tests.cpp
> +
Please create a folder tests/cpu/ops/gradinghuecurve and move the new modules into it.  This one should be named GradingHueCurveOpData_tests.cpp.

2024-06-10 18:03 UTC, larochj commented on src/OpenColorIO/ops/fixedfunction/FixedFunctionOpGPU.cpp
> -    shaderCreator->addToFunctionShaderCode(ss.string().c_str());
I added it after the call to GetFixedFunctionGPUProcessingText so it is still called in GetFixedFunctionGPUShaderProgram.

I created GetFixedFunctionGPUProcessingText so that the function op could be added after the bypass check un GradingHueCurveOpGPU::AddGCForwardShader

2024-06-10 20:38 UTC, larochj commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.h
> +    void computeKnotsAndCoefsBSpline(KnotsCoefs & knotsCoefs, int curveIdx) const;
I was keeping it so that it could be used from outside the class without knowing the BSpline type.
I was splitting computeKnotsAndCoefs so that the BSpline path is unnafected from what I'm adding (Mainly to debug/test). In syncolor both path (bspline and hue) seemed kept appart.

2024-06-11 13:01 UTC, larochj commented on include/OpenColorIO/OpenColorTransforms.h
> + * value. Will throw if property type is not DYNAMIC_PROPERTY_HUE_CURVE.
Fixed it

2024-06-11 13:02 UTC, larochj commented on include/OpenColorIO/OpenColorTransforms.h
> +class OCIOEXPORT DynamicPropertyHueCurve
Fixed it

2024-06-11 13:02 UTC, larochj commented on include/OpenColorIO/OpenColorTransforms.h
> +class OCIOEXPORT HueCurveTransform : public Transform
Fixed it

2024-06-11 13:05 UTC, larochj commented on include/OpenColorIO/OpenColorTransforms.h
> +    //virtual
Fixed it

2024-06-11 13:05 UTC, larochj commented on include/OpenColorIO/OpenColorTransforms.h
> +    // * but if there are several GradingPrimaryTransform only one can have dynamic parameters.
Fixed it

2024-06-11 13:06 UTC, larochj commented on include/OpenColorIO/OpenColorTypes.h
> +    TRANSFORM_TYPE_RANGE,
Fixed it

2024-06-11 13:08 UTC, larochj commented on include/OpenColorIO/OpenColorTypes.h
> +   HORIZONTAL_B_SPLINE
Fixed it

2024-06-11 13:27 UTC, larochj commented on src/OpenColorIO/DynamicProperty.cpp
> +    throw Exception("Dynamic property value is not a hue curve.");
Fixed it

2024-06-11 13:31 UTC, larochj commented on src/OpenColorIO/DynamicProperty.h
> +    // Holds curve data as knots and coefs. There is 8 curve.
Fixed it

2024-06-11 13:32 UTC, larochj commented on src/OpenColorIO/Op.cpp
> +                os << "Hue curve";
Fixed it

2024-06-11 13:33 UTC, larochj commented on src/OpenColorIO/fileformats/ctf/CTFReaderUtils.h
> +static constexpr char TAG_HUE_CURVE_HUE_HUE[] = "hue_hue";
Fixed it

2024-06-11 13:34 UTC, larochj commented on src/OpenColorIO/fileformats/ctf/CTFTransform.cpp
> +class HueCurveWriter : public OpWriter
Fixed it

2024-06-11 13:43 UTC, larochj commented on src/OpenColorIO/ops/gradinghuecurve/GradingHueCurve.cpp
> +    return m_curves[c];
Fixed it

2024-06-11 13:44 UTC, larochj commented on src/OpenColorIO/ops/gradinghuecurve/GradingHueCurve.h
> +class HueCurveImpl : public GradingHueCurve
Fixed it

2024-06-11 13:45 UTC, larochj commented on src/OpenColorIO/ops/gradinghuecurve/GradingHueCurve.h
> +#endif //INCLUDED_OCIO_GRADINGRGBCURVE_H
Fixed it

2024-06-11 13:45 UTC, larochj commented on src/OpenColorIO/ops/gradinghuecurve/GradingHueCurveOp.cpp
> +//#include "ops/gradingrgbcurve/GradingRGBCurveOpCPU.h"
Fixed it

2024-06-11 13:46 UTC, larochj commented on src/OpenColorIO/ops/gradinghuecurve/GradingHueCurveOp.cpp
> +    return "<HueCurveOp>";
Fixed it

2024-06-11 13:47 UTC, larochj commented on src/OpenColorIO/ops/gradinghuecurve/GradingHueCurveOp.cpp
> +                                        DynamicPropertyGradingRGBCurveImplRcPtr & prop)
Fixed it

2024-06-11 14:04 UTC, larochj commented on src/OpenColorIO/ops/gradinghuecurve/GradingHueCurveOpData.cpp
> +    m_style          = rhs.m_style;
Fixed it

2024-06-11 14:04 UTC, larochj commented on src/OpenColorIO/ops/gradinghuecurve/GradingHueCurveOpData.cpp
> +#include "ops/range/RangeOpData.h"
Fixed it

2024-06-11 14:04 UTC, larochj commented on src/OpenColorIO/ops/gradinghuecurve/GradingHueCurveOpData.h
> +typedef OCIO_SHARED_PTR<const HueCurveOpData> ConstHueCurveOpDataRcPtr;
Fixed it

2024-06-11 14:05 UTC, larochj commented on src/OpenColorIO/ops/gradinghuecurve/GradingHueCurveOpGPU.cpp
> +static const std::string opPrefix{ "huecurve" };
Fixed it

2024-06-11 14:05 UTC, larochj commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.h
> +        int m_nKnots = 0;
Fixed it

2024-06-11 14:13 UTC, larochj commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
> +   {
Seems to me like it match
This from ocio:
```
     // Copy a value from each side and wrap it around to the other side.
     GradingControlPoint firstCtrlPnt = outCtrlPnts[numCtrlPnts - 1];
     firstCtrlPnt.m_x -= 1.f;
     firstCtrlPnt.m_y = isHorizontal ? firstCtrlPnt.m_y : firstCtrlPnt.m_y - 1.f;
     outCtrlPnts.insert(outCtrlPnts.begin(), firstCtrlPnt);
```
is equivalent to this in syncolor:
```
x.insert(x.begin(), x[numCtrlPnts - 1] - 1.f);
y.insert(y.begin(), isHorizontal ? y[numCtrlPnts - 1] : y[numCtrlPnts - 1] - 1.f);
```

And this from ocio:
```
GradingControlPoint lastCtrlPnt = outCtrlPnts[1];
lastCtrlPnt.m_x += 1.f;
lastCtrlPnt.m_y = isHorizontal ? lastCtrlPnt.m_y : lastCtrlPnt.m_y + 1.f;
outCtrlPnts.push_back(lastCtrlPnt);
```
is equivalent to this from syncolor:
```
x.push_back(x[1] + 1.f);
y.push_back(isHorizontal ? y[1] : y[1] + 1.f);
```

2024-06-11 14:13 UTC, larochj commented on src/OpenColorIO/transforms/HueCurveTransform.cpp
> +#include "transforms/HueCurveTransform.h"
Fixed it

2024-06-11 21:56 UTC, larochj commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
@doug-walker, I'm no too sure how to handle GradingBSplineCurveImpl::isIdentity().

In SynColor we compare to the default curves for each Lin/Log and Red/Green/Blue/Master/Hue_Hue/Hue_Sat...
Should I replicate the same in GradingBSplineCurve? It would mean GradingBSplineCurve would need to know the HueCurveType or RGBCurveType.

Or remove GradingBSplineCurveImpl::isIdentity() and make it so the identity would be determined by the GradingRGBCurve class and the GradingHueCurve class before calling computeKnotsAndCoefs instead.

2024-06-12 04:45 UTC, doug-walker commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
It looks like you've added m_curveType to GradingBSplineCurveImpl, so we have the curve type available. Therefore, GradingBSplineCurveImpl::isIdentity() could use that to calculate the identity.

In SynColor isDefault compares to the specific vector of points that the curve was initialized with. In OCIO we wanted to improve on that and determine if the curve is really an identity, regardless of whether it matches the default values. 

Most of the curves are an identity when they are a diagonal line, in other words, when x[i] == y[i]. But there are a few curves that are horizontal. Here is how to check for each hue curve type:

Hue-Hue: diagonal (x[i] == y[i])
Hue-Sat: horizontal, y[i] == 1
Hue-Lum: horizontal, y[i] == 1
Lum-Sat: diagonal
Sat-Sat: diagonal
Lum-Lum: diagonal
Sat-Lum: horizontal, y[i] == 1
Hue-FX: : horizontal, y[i] == 0

2024-06-12 05:12 UTC, doug-walker requested changes

2024-06-12 14:19 UTC, larochj commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
m_curveType is a BSplineCurveType, to differentiate horizontal at y[i]=0 and y[i]=1, I'll have to switch it to a CurveType enum that I'll create from the RGBCurveType and the HueCurveType. 

Or keep it a BSplineCurveType and add an identityY attribute, to avoid adding hue and rgb specifics to the class.

2024-06-12 17:46 UTC, doug-walker commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
Good point. I don't like the identityY option.  Perhaps have separate BSplineCurveTypes:
HORIZONTAL0_B_SPLINE
HORIZONTAL1_B_SPLINE

2024-06-13 19:47 UTC, larochj commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
> +void GradingBSplineCurveImpl::AddShaderEvalHueCurve(GpuShaderText & st,
Should I replace past one in AddShaderEval (use 2 parameters) with the one in AddShaderEvalHueCurve (Use 3 parameters, there's one for identity_x)?

2024-06-14 03:18 UTC, doug-walker commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
> +void GradingBSplineCurveImpl::AddShaderEvalHueCurve(GpuShaderText & st,
Yes, the three-parameter version may be used everywhere. Simply pass in the x argument as the third parameter when using it for RGB curves.

2024-06-14 15:57 UTC, larochj commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
Fixed, I end adding HORIZONTAL1_B_SPLINE and PERIODIC_HORIZONTAL1_B_SPLINE and the 0 identity ones too.

2024-06-14 17:27 UTC, larochj commented on include/OpenColorIO/OpenColorTypes.h
> +    DYNAMIC_PROPERTY_GRADING_HUECURVE  ///< Used by GradingToneTransform
Fixed

2024-06-14 17:27 UTC, larochj commented on src/OpenColorIO/Op.h
> +        throw Exception("Op does not implement grading rgb curve dynamic property.");
Fixed

2024-06-14 17:28 UTC, larochj commented on src/OpenColorIO/OpBuilders.h
> +void BuildHueCurveOp(OpRcPtrVec & ops,
Fixed

2024-06-14 17:29 UTC, larochj commented on src/OpenColorIO/ops/gradinghuecurve/GradingHueCurveOp.cpp
> +    return std::make_shared<GradingHueCurveOp>(p);
Fixed

2024-06-14 17:31 UTC, larochj commented on tests/cpu/transforms/HueCurveTransform_tests.cpp
> +// Copyright Contributors to the OpenColorIO Project.
Fixed

2024-06-14 17:33 UTC, larochj commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
> +  //------------------------------------------------------------------------------------------------
Fixed

2024-06-14 17:34 UTC, larochj commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
> +//------------------------------------------------------------------------------------------------
Fixed moved them into the anonymous namespace used for other similar functions

2024-06-14 17:36 UTC, larochj commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
> +void EstimateSlopesBSpline(const std::vector<GradingControlPoint> & ctrlPnts, std::vector<float> & slopes)
Fixed, renames both these function using RGB instead

2024-06-14 17:37 UTC, larochj commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
> +BSplineCurveType GradingBSplineCurveImpl::getCurveType() const
Fixed

2024-06-14 17:37 UTC, larochj commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
> +    estimateHueSlopes(resultCtrlPnts, slopes, isPeriodic, isHorizontal);
Fixed

2024-06-14 18:20 UTC, larochj commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
> +void GradingBSplineCurveImpl::AddShaderEvalHueCurve(GpuShaderText & st,
Fixed

2024-06-15 02:52 UTC, doug-walker commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
>      {
This if/else should be refactored, if there's nothing in the if part.

2024-06-15 02:52 UTC, doug-walker commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
>          FitSpline(m_controlPoints, slopes, knots, coefsA, coefsB, coefsC);
FitSpline --> FitRGBSpline
AdjustSlopes --> AdjustRGBSlopes

2024-06-15 02:52 UTC, doug-walker commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
>      const int coefsSets = m_coefsOffsetsArray[2 * c + 1] / 3;
On line 1008 and 1056 (return x & return y), please add:
TODO: Update to return hue curve identity value.

2024-06-15 02:52 UTC, doug-walker commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
> +bool IsDiagonalControlPoint( const GradingControlPoint& cp )
Given that these are only used in isIdentity, it would be nice if they were declared next to or inside that. Could they be lambdas?  Does that work with std:all_of?

2024-06-15 02:52 UTC, doug-walker commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
> +} // anonymous namespace
You could remove this first namespace, since it's empty.

2024-06-15 02:52 UTC, doug-walker commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
> +  //------------------------------------------------------------------------------------------------
The functions PrepHueCurveData, CalcKsi, FitHueSpline, EstimateHueSlopes, are still using SynColor 2-space indentation, rather than OCIO 4-space indentation.

2024-06-15 03:42 UTC, doug-walker requested changes

2024-06-15 03:42 UTC, doug-walker commented on include/OpenColorIO/OpenColorTypes.h
> +   HORIZONTAL0_B_SPLINE            //!< Non-monotonic B-spline, centered at 0, used for HueFX curve.
Sorry, I duplicated Horizontal, when it was actually Periodic that needs the separate modes. Please update as follows:

```
      B_SPLINE = 0,           //!< Monotonic quadratic B-spline used for the RGBM curves.
      DIAGONAL_B_SPLINE,      //!< Monotonic quadratic B-spline for the sat-sat and lum-lum curves.
      HUE_HUE_B_SPLINE,       //!< Monotonic and periodic B-spline used for the hue-hue curve.
      PERIODIC_1_B_SPLINE,    //!< Periodic, horizontal (at 1) B-spline for hue-sat and hue-lum curves.
      PERIODIC_0_B_SPLINE,    //!< Periodic, horizontal (at 0) B-spline used for the hue-fx curve.
      HORIZONTAL_1_B_SPLINE   //!< Horizontal (at 1) B-spline used for the lum-sat and sat-lum curves.
```

2024-06-17 15:00 UTC, larochj commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
> +  //------------------------------------------------------------------------------------------------
Oh sorry misread that, those four functions should be good now

2024-06-17 15:05 UTC, larochj commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
> +BSplineCurveType GradingBSplineCurveImpl::getCurveType() const
Moved the implementation too now (I only move the declaration in the .h before)

2024-06-17 15:27 UTC, larochj commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
>      {
Fixed, it was not supposed to be empty

2024-06-17 15:30 UTC, larochj commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
>          FitSpline(m_controlPoints, slopes, knots, coefsA, coefsB, coefsC);
Fixed

2024-06-17 15:50 UTC, larochj commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
> +bool IsDiagonalControlPoint( const GradingControlPoint& cp )
Fixed, using lambdas instead

2024-06-17 15:51 UTC, larochj commented on src/OpenColorIO/ops/gradingrgbcurve/GradingBSplineCurve.cpp
> +} // anonymous namespace
Fixed

2024-06-17 17:48 UTC, larochj commented on include/OpenColorIO/OpenColorTypes.h
> +   HORIZONTAL0_B_SPLINE            //!< Non-monotonic B-spline, centered at 0, used for HueFX curve.
Fixed

2024-06-18 03:27 UTC, doug-walker requested changes
Thanks for the fixes, making great progress!

2024-06-18 03:27 UTC, doug-walker commented on src/OpenColorIO/ops/gradinghuecurve/GradingHueCurveOpData.h
> +    bool hasChannelCrosstalk() const override { return false; }
This should return true.

2024-06-18 03:27 UTC, doug-walker commented on tests/cpu/ops/gradinghuecurve/GradingHueCurveOpData_tests.cpp
> +    OCIO_CHECK_ASSERT(!gc.hasChannelCrosstalk());
Thanks for starting to get the tests working. This helped me notice a bug.

Are these tests based on ones in SynColor?  It would help me with the review if you could add temporary comments that points me back to which files they originated from in SynColor.

2024-06-18 03:56 UTC, doug-walker commented
I ran the CI and the build is failing. We have it set up so that any unhandled enums in a case statement is an error. So there are some FixedFunction switch statements that need to be fixed to handle the new enum values like RGB_TO_HSY_LOG.

2024-06-18 17:02 UTC, larochj commented
> I ran the CI and the build is failing. We have it set up so that any unhandled enums in a case statement is an error. So there are some FixedFunction switch statements that need to be fixed to handle the new enum values like RGB_TO_HSY_LOG.

I think I fixed the remaining switch case error and unused parameters

2024-06-19 01:51 UTC, doug-walker approved these changes
Everything here looks good. Of course, there is a lot left unfinished, so we should discuss what the next steps are.  I guess you have everything you need for Flame at this point?

Regarding the tests, one of the macOS runners failed, but you may ignore it as it's not related to your work.  The Windows runners failed due to your code, but I don't know if the error log is sufficiently obvious to fix it or if it needs to be fixed on a Windows computer?  Please let me know.

2024-06-20 19:30 UTC, merged