Cozdas/nanocolor/add lut switch
autodesk-forks/OpenColorIO pull request #6
Opened 2024-06-10 18:31 UTC by cozdas

- Adding OCIO_LUT_AND_FILETRANSFORM_SUPPORT cmake switch which will turn on/off LUT and File Transform features. Turning this off will remove the expat dependency. 
-- Currently when this is turned off, the python project won't compile successfully. 
-- When this feature is turned off, the project that make sense only with LUT support will be removed from the build: ociobakelut, ociochecklut, ociomakeclf and ociolutimage.
-- At this stage the tests will compile fine with this option off but they may not succeed. 

- some cleanup related to OCIO_ARCHIVE_SUPPORT flag.

2024-06-11 03:21 UTC, doug-walker requested changes
I moved the unresolved comments from the PR on the private repo to here, so we're able to focus on just this one PR.

2024-06-11 03:21 UTC, doug-walker commented on tests/cpu/ops/noop/NoOps_tests.cpp
> +// TODO Nano: some tests may not be needing the LUT, those can be enabled. /coz
Please remove the todo.

2024-06-11 03:21 UTC, doug-walker commented on tests/cpu/apphelpers/DisplayViewHelpers_tests.cpp
> +#if OCIO_LUT_AND_FILETRANSFORM_SUPPORT
I'm not clear on why you have nested your ifs here. Could you remove this outer one?

2024-06-11 20:02 UTC, cozdas commented on src/apps/ocioconvert/main.cpp
> +				exit(1);
Hmm visual studio IDE supposed to do adaptive "TAB" vs "spaces" selection and should pick "spaces" for OCIO sources as they are space based (except for some cmake files and few exceptions here and there). Looks like that doesn't work robustly. I need to keep an eye on the whitespace before committing.

2024-06-11 23:12 UTC, cozdas commented on src/OpenColorIO/fileformats/ctf/CTFTransform.cpp
> +#include "transforms/CDLTransform.h"
Ooops! Good catch. I need to learn not to mixup CTF and CDL, which happened before.

2024-06-11 23:15 UTC, cozdas commented on tests/cpu/fileformats/FileFormatCDL_tests.cpp
> +// TODO Nano: add non-file tests for CDL. /coz
you are right, missed that fact that we have tests for non-file parts of CDL

2024-06-11 23:16 UTC, cozdas commented on tests/cpu/apphelpers/DisplayViewHelpers_tests.cpp
> +#if OCIO_LUT_AND_FILETRANSFORM_SUPPORT
Leftover from multiple passes of compile errors. Good catch!

2024-06-13 04:12 UTC, cozdas commented on src/OpenColorIO/Transform.cpp
>      else if(ConstCDLTransformRcPtr cdlTransform = \
Located more places that the non-file CDL transform was disabled. I hope not got them all. Please re-check.

2024-06-13 04:12 UTC, cozdas commented on src/OpenColorIO/fileformats/FileFormatVF.cpp
> +
Should be done, please re-check.

2024-06-13 04:14 UTC, cozdas commented on src/OpenColorIO/fileformats/ctf/CTFTransform.cpp
> +#if OCIO_LUT_AND_FILETRANSFORM_SUPPORT
Was a leftover from multiple iterations. Should be fixed.

2024-06-13 04:14 UTC, cozdas commented on src/OpenColorIO/ops/cdl/CDLOp.cpp
> +
All cleaned up. Please re-check.

2024-06-13 04:19 UTC, cozdas commented on src/OpenColorIO/transforms/CDLTransform.h
> +
yup leftover from multiple iterations. I will revert.

2024-06-13 04:21 UTC, cozdas commented on src/OpenColorIO/transforms/GroupTransform.cpp
> +	return nullptr;
Seems like visual studio is not obeying the settings, I've searched for tab characters and untabified them. I haven't touched the existing ones though (mostly CmakeLists.txt files with few others here and there).

2024-06-13 04:21 UTC, cozdas commented on src/OpenColorIO/transforms/Lut3DTransform.h
> +#endif //OCIO_LUT_AND_FILETRANSFORM_SUPPORT
Should be fixed now.

2024-06-13 04:25 UTC, cozdas commented on src/OpenColorIO/transforms/builtins/BuiltinTransformRegistry.cpp
> +	CAMERA::ARRI::RegisterAll(*this);
Should be unified now.

2024-06-13 04:30 UTC, cozdas commented on tests/cpu/ops/noop/NoOps_tests.cpp
> +// TODO Nano: some tests may not be needing the LUT, those can be enabled. /coz
enabled the tests that don't need LUT support. will push soon.

2024-06-14 04:44 UTC, doug-walker commented on src/OpenColorIO/ConfigUtils.cpp
> +#endif // OCIO_LUT_AND_FILETRANSFORM_SUPPORT
You could just have the whole containsBlockedTransform function return false. The whole point is to avoid LUTs and files, but those aren't allowed in nano.

2024-06-14 04:44 UTC, doug-walker commented on src/OpenColorIO/Transform.cpp
> +#if OCIO_LUT_AND_FILETRANSFORM_SUPPORT //TODO Nano: throw?
Do we need the todo?  There won't be any way to arrive here, right?

2024-06-14 04:44 UTC, doug-walker commented on src/OpenColorIO/ops/cdl/CDLOp.cpp
> +
Things look much neater now, so thanks for that!  But I still would advise reverting CDLOp.h and CDLOp.cpp entirely.

2024-06-14 05:23 UTC, doug-walker requested changes
Making great progress!

2024-06-14 05:23 UTC, doug-walker commented on tests/cpu/apphelpers/DisplayViewHelpers_tests.cpp
> +// TODO Nano: can enable some tests that doesn't require file
Please remove the TODO. This is true in general, but these particular tests are not that important.

2024-06-14 05:23 UTC, doug-walker commented on tests/cpu/ops/noop/NoOps_tests.cpp
> +// #if OCIO_LUT_AND_FILETRANSFORM_SUPPORT
Remove commented line.

2024-06-14 05:23 UTC, doug-walker commented on src/libutils/oglapphelpers/glsl.cpp
>  }
AllocateTexture3D should be ifdefed too?

I notice in some cases you are removing the whole function and in others just the contents of the function. What is the strategy there?

2024-06-14 06:10 UTC, cozdas commented on src/OpenColorIO/Transform.cpp
> +#if OCIO_LUT_AND_FILETRANSFORM_SUPPORT //TODO Nano: throw?
We should not, and if we do, there is a throw at the end anyhow.

2024-06-14 19:58 UTC, cozdas commented on src/OpenColorIO/ConfigUtils.cpp
> +#endif // OCIO_LUT_AND_FILETRANSFORM_SUPPORT
done.

2024-06-14 19:59 UTC, cozdas commented on src/OpenColorIO/OpOptimizers.cpp
> +#if OCIO_LUT_AND_FILETRANSFORM_SUPPORT
done

2024-06-14 19:59 UTC, cozdas commented on src/OpenColorIO/Transform.cpp
> +    if (DynamicPtrCast<const ExponentOpData>(data))
done

2024-06-14 20:01 UTC, cozdas commented on src/OpenColorIO/transforms/builtins/Displays.cpp
> +    // TODO Nano: do we need this? /coz
done

2024-06-14 20:01 UTC, cozdas commented on tests/cpu/apphelpers/DisplayViewHelpers_tests.cpp
> +// TODO Nano: can enable some tests that doesn't require file
done

2024-06-14 20:01 UTC, cozdas commented on tests/cpu/ops/noop/NoOps_tests.cpp
> +// #if OCIO_LUT_AND_FILETRANSFORM_SUPPORT
done

2024-06-14 20:20 UTC, cozdas commented on src/libutils/oglapphelpers/glsl.cpp
>  }
In this particular file the class member functions, were converted to no-op, and the functions which were visible only in this file's scope were totally removed. This way the clients that use OpenGLBuilder class didn't have to change.

But since recently we moved to "removing the interfaces which doesn't make sense without LUT support" strategy, In the latest commit I just ifdef'ed the class member functions too. This will give compile time errors if the client tries to engage with texture functions for LUT support, so clearer than the no-op approach in terms of what's available in the Nano edition. But will require the clients to update their code for OCIONano if they use OpneGLBuilder.

Since I don't have ways to compile/test then, I haven't updated the MetalBuilder which copies what OpenGlBuild does, not updated OpenColorIO_AE_Context which seems to use OpenGLBuilder class. 

Let me know if you prefer keeping the OpenGlBuilder inerfact intact. Also please advise what to do with metal and AE files/projects.

2024-06-14 20:33 UTC, cozdas commented
I addition to the tests, as we discussed I did manual tests on the gpu rendering when the lut support is off. both the cpu and gpu paths produce the same results in the command line converter tool, the viewer also works fine (as long as the config doesn't need one of the removed transforms of course).

State of the MetalBuilder or any other project that's not covered in the standard windows build or CI tests are unknown at this stage.

2024-06-15 04:22 UTC, doug-walker reviewed
Yay, looks great!

The last item I'm wondering about is related to the GPU API. 

There are trade-offs.  On the one hand, totally removing the texture functions makes it clear what is not supported or required in nano.  However, I'm thinking about Jerry's plug-in for MaterialX.  And there may be some other similar clients that would like to be able to link against either nano or OCIO.  If we remove the functions, they will need to ifdef there code too.  Whereas if we leave the API but just have it do nothing, they could leave their side unchanged.  

What are your thoughts on that?

2024-06-17 18:48 UTC, cozdas commented
For the GPU interface I'm torn as well, 
On one hand we want to make the nano usage simpler and free from textures, and it'd be best if that's obvious in the API, otherwise the developers of the client apps may think that OCIO nano still uses textures internally, might be a deterring misunderstanding. This is an argument for removing those functions from the API

But on the other hand, as you have indicated, keeping them around will make the nano<->full OCIO switch very smooth. This is an argument for keeping them around. 

Maybe we can keep them for compatibility but make it obvious in the header that they are no-ops in nano edition. Let's discuss offline.

2024-06-20 21:09 UTC, doug-walker approved these changes
Nice work!

2024-06-24 16:56 UTC, merged