Fix Windows CI
autodesk-forks/OpenColorIO pull request #8
Opened 2024-06-21 12:02 UTC by larochj

2024-06-26 03:16 UTC, doug-walker requested changes
Thanks for fixing the Windows build break.

For the slopes, please don't modify the size of m_slopesArray. The client must always provide the same number as the control points. But for periodic curves, the slopes should be duplicated at each end, the same as the control points. This could either be done in PrepHueCurveData or at line 817 in computeKnotsAndCoefsForHueCurve. And you should use the existing isPeriodic variable rather than trying to calculate it separately, since your added code is not doing it correctly.  Thanks!

2024-06-27 02:21 UTC, doug-walker approved these changes

2024-06-27 02:21 UTC, doug-walker commented on src/OpenColorIO/ops/gradinghuecurve/GradingHueCurveOpData.cpp
> +#include <iostream>
Is iostream needed?

2024-06-27 13:18 UTC, larochj commented on src/OpenColorIO/ops/gradinghuecurve/GradingHueCurveOpData.cpp
> +#include <iostream>
Removed it, it was a leftover from debugging

2024-06-27 17:19 UTC, merged